#!/usr/bin/env bash
#this is first loop
hour=0

 

while [ $hour -le 12 ]

do

    echo "Hour: $hour"

 

    minute=1

 #!/usr/bin/env bash
#this is first loop
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
        while [ $minute -le 59 ]
    do
    echo $minute
        ((minute++))
    done
    ((hour++))
done
