#!/usr/bin/env bash
# kill 10-process_and_pid_file
sudo bash -c "echo $$ > /var/run/myscript.pid"
# Define trap handlers for signals
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo " OK "; sudo rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'sudo rm -f /var/run/myscript.pid; exit' SIGQUIT
# Infinite loop
while :
do
echo "To infinity and beyond"
 sleep 2
done



 
